### ISSUE TITLE
IOS Build Failed (Xcode >= 11.3)

### ISSUE THREAD

**Issue by Stanteq** [jibon57/nativescript-mediafilepicker#106]
Hi, I have a problem with a IOS when I try to build my application after updating the Xcode to the version 11.3 and now 11.4. It's related to DKImagePickerController, bunch of Swift compiler errors.

For example:

```
'pngData()' has been renamed to 'UIImagePNGRepresentation(_:)'
...
'jpegData(compressionQuality:)' has been renamed to 'UIImageJPEGRepresentation(_:_:)'
...
etc
```

**Comment by jibon57** [comment]
It's native library related error. You can open issue in native library repo

**Comment by Stanteq** [comment]
@jibon57, Thx the author of native library comes [here](https://github.com/zhangao0086/DKImagePickerController/issues/648#issuecomment-607618561) with a fix. There is a way to force the Swift version with the plugin directly?

**Comment by jibon57** [comment]
@Stanteq thank you. Will you please try this?

**Comment by jibon57** [comment]
@Stanteq thank you. Will you please try to follow this article: https://medium.com/@championswimmer/setting-swift-version-in-nativescript-6ece09112a46

**Comment by jibon57** [comment]
I think it's better to set `DKImagePickerController` for swift 5.

pre_install do |installer|
    installer.analysis_result.specifications.each do |s|
        if s.name == 'DKImagePickerController'
            s.swift_version = '5.0'
        end
    end
end

**Comment by Stanteq** [comment]
@jibon57, thank you.

> ```
> post_install do |installer|  
> 	installer.pods_project.targets.each do |target|    
> 		target.build_configurations.each do |config|      
> 			config.build_settings['SWIFT_VERSION'] = '5.0'     
> 		end   
> 	end
> end
> ```

This sets the desired version for all pods (but in my case breaks other ones which are required a different version)


> ```
> pre_install do |installer|
>     installer.analysis_result.specifications.each do |s|
>         if s.name == 'DKImagePickerController'
>             s.swift_version = '5.0'
>         end
>     end
> end
> ```

This has no effect. The swift version remains 4

**Comment by OPADA-Eng** [comment]
I got it to work finally with the following steps:
1. change the pod file in the plugin nativescript-web-image-cache to 

> pod 'SDWebImage', '~> 5.9.0'

2. add the below to app/App_Resources/iOS/Podfile :
`post_install do |installer|
  installer.pods_project.targets.each do |target|
    if target.name == 'DKImagePickerController'
      target.build_configurations.each do |config|
        config.build_settings['SWIFT_VERSION'] = '5.0'
      end
    end
  end
end`
This should fix the error and build the project.
