### ISSUE TITLE
Custom File Picker in iOS giving error while copying pdf file to app directory.

### ISSUE THREAD

**Issue by Shubhangvanjani** [jibon57/nativescript-mediafilepicker#107]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**NativeScript Info(please run `tns info`):**

**Sample Code(please provide minimum code to reproduce problem):**

**Additional context**

**Comment by jibon57** [comment]
Didn't follow template

**Comment by erkanarslan** [comment]
I have the same problem
