### ISSUE TITLE
Dialog not closing on selection in iOS

### ISSUE THREAD

**Issue by dotnetdreamer** [jibon57/nativescript-mediafilepicker#11]
I have added the dialog picker in iOS. but when i choose large video it isn't closing the picker. The done button is doing nothing.
Also for small video size, getting following error:

`TypeError: undefined is not an object (evaluating 'uri.toString')`

**Comment by dotnetdreamer** [comment]
I am not sure why, but i just debugged it and this line of code when i hide the if condition then it works fine.

```
- (void)finishPickingAssets:(id)sender
{
//    if ([self.delegate respondsToSelector:@selector(assetsPickerController:didFinishPickingAssets:)]) {
        [self.delegate assetsPickerController:self didFinishPickingAssets:self.selectedAssets];
//    }
}
```

**Comment by bachras** [comment]
@dotnetdreamer I can't find the file with code lines you mentioned. What is exact location of the file? Thanks in advance

**Comment by jibon57** [comment]
@bachras he had mentioned this line: https://github.com/TechSmith/GMImagePicker/blob/03aba04098806af4f6da93ccc0353c9447d9deb2/GMImagePicker/GMImagePickerController.m#L220

Actually that library has few problem & I don't have enough idea to solve it now. You can try to adjust main library.

**Comment by bachras** [comment]
@jibon57 thank you for prompt response. I haven't changed main library before. How do I approach that? Do I have to download this plugin with library and amend the files and try to install plugin from local machine? Could you walk me through?  Thanks in advance.

**Comment by dotnetdreamer** [comment]
hi @bachras  with alittle bit of reasearch, i guess the issue isn't this library. When you open the filterpicker sometimes its closing and sometimes itsn't. I had same issue before with openning UIPIckerView in iOS for PDF files. So what i did is i checked the existing plugins, and it turns out that the instance of delegate isn't retained. 
Take a look at [this](https://github.com/jibon57/nativescript-mediafilepicker/blob/e9eb1daa444448312811149043744fba4daeb08e/src/mediafilepicker.ios.ts#L40) line in your code. This instance is destroyed. So what you need to do is to try it like [this](https://github.com/NativeScript/nativescript-imagepicker/blob/43405a60012ebc8101bc181fe44c3c2ca6610b02/src/imagepicker.ios.ts#L21). So simply the retain the instance of delegate at the top of class in private variable so that Objective-C runtime doesn't destroy it.  I found same things in other TNS plugins too.

**Comment by dotnetdreamer** [comment]
@bachras @jibon57  [check](https://discourse.nativescript.org/t/video-picker-delegate-doesnt-fire-method/5452/2) this topic on forum. It resolved my issue.

**Comment by jibon57** [comment]
@dotnetdreamer thanks for it. I will be happy if you give any pull request.

**Comment by jibon57** [comment]
@dotnetdreamer I have tested the way you have explained. Unfortunately I haven't get any success. But I have seen that if I disabled multiple selection then it worked as expected. So, if you have anything work around then you can share with me here.

**Comment by jibon57** [comment]
Try new version
