### ISSUE TITLE
rawData is empty or contains com.vincent.filepicker.filter.entity.ImageFile entiry

### ISSUE THREAD

**Issue by ericreinke** [jibon57/nativescript-mediafilepicker#112]
When I dump the results from the picker I get 
```
==== object dump start ====
type: "image"
file: "/storage/emulated/0/DCIM/IMG_202068_113845.jpg"
rawData: com.vincent.filepicker.filter.entity.ImageFile@6aaa316c
==== object dump end ====
```

 I tried the demo app and there rawData is empty.  My end goal is to retrieve the image in base64 format but I'm not sure if I'm misunderstanding the results and how to proceed

**Comment by tranindigo** [comment]
For future references: I also got this error when on Android. It means that your app does not have permissions to the Android filesystem. What I did was add `android:requestLegacyExternalStorage="true"` to `AndroidManifest.xml` and it worked.
