### ISSUE TITLE
getFiles is not always triggered on ios

### ISSUE THREAD

**Issue by sleepychaman** [jibon57/nativescript-mediafilepicker#114]
**Describe the bug**

When calling `openFilePicker` getFiles is not triggered the first time i choose a file (icloud or not) and some times even the second times.

**To Reproduce**
select a file (icloud or not) in ios

**Expected behavior**
I expect getFiles to be triggered each time i select a file (icloud or not)

**NativeScript Info(please run `tns info`):**

`✔ Getting NativeScript components versions information...
⚠ Update available for component nativescript. Your current version is 6.5.0 and the latest available version is 6.7.4.
⚠ Update available for component tns-core-modules. Your current version is 6.5.1 and the latest available version is 6.5.7.
⚠ Update available for component tns-android. Your current version is 6.5.0 and the latest available version is 6.5.1.
⚠ Update available for component tns-ios. Your current version is 6.3.0 and the latest available version is 6.5.1.`

**Sample Code(please provide minimum code to reproduce problem):**
`    let extensions = [];

    if (isIOS) {
      extensions = [kUTTypePDF]; // you can get more types from here: https://developer.apple.com/documentation/mobilecoreservices/uttype
    } else {
      extensions = ['pdf'];
    }

    const options: FilePickerOptions = {
      android: {
        extensions,
        maxNumberFiles: 1,
      },
      ios: {
        extensions,
        multipleSelection: false,
      },
    };

    const mediafilepicker = new Mediafilepicker();
    mediafilepicker.on('getFiles', async res => {
      this.ngZone.run(() => {
        const results = res.object.get('results');
        console.log(results);
      });
    });

    mediafilepicker.on('error', res => {
      const msg = res.object.get('msg');
      this.logger.error('Upload error : ', msg);
      this.toggleSelector();
    });

    mediafilepicker.on('cancel', res => {
      console.log('cancel', res);
    });

    mediafilepicker.openFilePicker(options);`

**Additional context**
`documentPickerDidPickDocumentsAtURLs` is not called so thats why getFiles is not triggered, I try to resolve it and make a PR, but I can't make it work.
PS: Thanks for this plugin !

**Comment by paul-castro** [comment]
got same issue on iOS, actually it happens very randomly (not always).

is there any solution for this?

or is there a function where I can detect if the "file browser/directory" closed?

**Comment by kriefsacha** [comment]
Same thing here... On IOS at first getFiles is not called, then if i call another one it's called

**Comment by kriefsacha** [comment]
Moved all the "on" to ngOnInit (i'm on nativescript-angular), and called the openFilePicker only on click of button and it fixed for me

**Comment by paul-castro** [comment]
yeah, I think seperating the openFilePicker method from other plugin's methods will do the trick

**Comment by erkanarslan** [comment]
I have this problem too. Also error and cancel callbacks are sometimes not called as well.

**Comment by kriefsacha** [comment]
Try to do as i saied @erkanarslan , put the "on's" functions and initialisation on the beginning and call the openFilePicker like on a button click or something

**Comment by erkanarslan** [comment]
Filepicker is used in many places in my app. Because of that I put it into a service. I cannot do that.

**Comment by kriefsacha** [comment]
So initialize it in your service

**Comment by erkanarslan** [comment]
@kriefsacha I tried that and it works. Instead of creating a new filepicker instance each time, I created one instance and used it for all operations.

**Comment by davecoffin** [comment]
This saved me guys thanks!
