### ISSUE TITLE
Build faild with xcode 11.5

### ISSUE THREAD

**Issue by OPADA-Eng** [jibon57/nativescript-mediafilepicker#116]
**Describe the bug**
Hi, Thanks for this plugin, but there is a problem when building for ios and it's showing error regarding rename functions in DKImagePickerController
**To Reproduce**
try to build an app using this plugin

**Expected behavior**
Build failed

**NativeScript Info(please run `tns info`):**
"tns-core-modules": "~6.5.0",
"tns-ios": {
      "version": "6.5.1"
    }

**Sample Code(please provide minimum code to reproduce problem):**

**Additional context**

**Comment by jibon57** [comment]
Didn't follow template
