### ISSUE TITLE
[Android] No audio recorder app installed!

### ISSUE THREAD

**Issue by sido420** [jibon57/nativescript-mediafilepicker#122]
I'm not sure if this a bug or a feature request or usability issue.

I am trying to open the Audio recorder but I get this error instead
```
 No audio recorder app installed!
```
However, other apps allow audio recording on the same device. 

```
    mediafilepicker.on("error", filePickerErrorCB);
```

I can share environment details if you confirm that this is a bug.

Thanks.

**Comment by jibon57** [comment]
This is simple that your simulator or device doesn't have installed any recording app.
