### ISSUE TITLE
NS7 and iOS 14 Support

### ISSUE THREAD

**Issue by msaravitz** [jibon57/nativescript-mediafilepicker#124]
After resolving the @nativescript/core import changes,  It seems that  DKImagePickerController has a few errors. Is iOS 14 currently just not supported or am I missing something? Thanks!

**Comment by coderaven** [comment]
> After resolving the @nativescript/core import changes, It seems that DKImagePickerController has a few errors. Is iOS 14 currently just not supported or am I missing something? Thanks!

I am experiencing the same issue. Media File Picker breaks on IOS 14

**Comment by csimpi** [comment]
After upgrading to Angular 70, NS7, Android, breaks the app:

` TypeError: Class constructor Observable cannot be invoked without 'new'
`

**Comment by csimpi** [comment]
@jibon57 When can we expect any updates for this package?

**Comment by jerbob92** [comment]
I migrated this plugin to NS7 in #126, don't know about iOS 14 though.

**Comment by jerbob92** [comment]
I just published 4.0.0 for NS 7 support.
