### ISSUE TITLE
No way to tell if picker is closed without picking images

### ISSUE THREAD

**Issue by Burgov** [jibon57/nativescript-mediafilepicker#14]
If i use the caret-left icon or the android back button to back out of the picker, I have no way to tell that this happened. No events are fired

**Comment by jibon57** [comment]
The main library haven't left any option for that. Last time I added a default in case switch option. But it had created this problem: https://github.com/jibon57/nativescript-mediafilepicker/issues/2
Then I had fixed it here: https://github.com/jibon57/nativescript-mediafilepicker/commit/607d824ac5e615593cc444ed290ea1146219984e
So, you can do customization for your needs.
