### ISSUE TITLE
Plugin code overrides native activity result callback

### ISSUE THREAD

**Issue by lini** [jibon57/nativescript-mediafilepicker#15]
The code, which handles the activity result on Android incorrectly overrides the base NativeScript result callback. This means that any other code in the app that launches an activity will not be able to receive its result. The place where this happens is https://github.com/jibon57/nativescript-mediafilepicker/blob/607d824ac5e615593cc444ed290ea1146219984e/src/mediafilepicker.android.ts#L58

For the correct way to handle results from activities, you can refer to the documentation https://docs.nativescript.org/core-concepts/application-lifecycle#android-activity-events

**Comment by jibon57** [comment]
@lini thanks for pointing out it. I will resolve it.
