### ISSUE TITLE
onActivityResult conflicts

### ISSUE THREAD

**Issue by Sharique-Hasan** [jibon57/nativescript-mediafilepicker#2]
Thank you for your plugin. It resolved many of my issues.

I am facing a strange issue. When I open picker and select an image. Then I go for any other plugin which uses activityResult callback then your callback gets fired. I spent time figuring it out. But failed to do so. More precisely I have to login with facebook with nativescript-facebook but it's callback falls into your callback and gives me error because of the switch case implemented.

**Comment by jibon57** [comment]
Thanks for report. Will fix the issue but you can comment out following lines (108 to 115):

https://github.com/jibon57/nativescript-mediafilepicker/blob/1cb6003a5fd83c91eda14975de9a2abf9b50c958/src/mediafilepicker.android.ts#L108
