### ISSUE TITLE
Getting Error in Android as Could not find method implementation() for arguments [com.android.support:appcompat-v7:27.1.1]

### ISSUE THREAD

**Issue by san18793** [jibon57/nativescript-mediafilepicker#20]
Hi, 
I downloaded the demo app and added the platform android , After that I ran the project using tns run android.when I do this I am getting the following error

Could not find method implementation() for arguments [com.android.support:appcompat-v7:27.1.1] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.

Is there any changes I need to do in Android Studio to make it works..

**Comment by jibon57** [comment]
@san18793, You will need Gradle 3.4 or later. Do like this:

```
tns platform remove android
tns prepare android
tns run android
```

**Comment by san18793** [comment]
I am having Gradle 4.1 and followed your step too. Still getting the same error.

**Comment by jibon57** [comment]
Not sure why you are getting that error. You can change `include.gradle` items from `implementation` to `compile`. The location of `include.gradle` is 'src/platforms/android'. After that follow https://github.com/jibon57/nativescript-mediafilepicker/issues/20#issuecomment-408610873

**Comment by san18793** [comment]
I can't able to use your plugin into my project, I am using Nativescript Version - 3.4.3 for android, and your plugin version is "nativescript-mediafilepicker": "^1.0.7", and angular version  - 5.2.0 but still getting the same error Could not find method implementation() for arguments [com.android.support:appcompat-v7:27.1.1] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler

**Comment by jibon57** [comment]
Try latest nativescript or use older version of this plugin. 
`tns plugin add nativescript-mediafilepicker@1.0.6`

**Comment by san18793** [comment]
Thanks its working fine
