### ISSUE TITLE
I need example in JS

### ISSUE THREAD

**Issue by dyazincahya** [jibon57/nativescript-mediafilepicker#22]
how to convert this code to javascript?

import { Mediafilepicker, MediaFilepickerOptions } from 'nativescript-mediafilepicker';
    private mediafilepicker;
    
    let options: MediaFilepickerOptions = {
      android: {
        mxcount: 2,
        enableImagePicker: true,
        enableVideoPicker: true,
        enableCameraSupport: true,
      },
      ios: {
        allowsMultipleSelection: true,
        title: "Album",
        showCameraButton: true,
      }
    };
    this.mediafilepicker = new Mediafilepicker();

    this.mediafilepicker.on("getFiles", function (res: any) {
 
      let files = res.files;

      if (files.length > 0) {

        files = files.split(",");

        files.forEach(file => {

          let fileName = file.replace(/^.*[\/]/, '');

          console.log(file);
          console.log(fileName);

          // you can do anything here

          if (app.ios) {

            let folder = fs.knownFolders.documents();
            let file = folder.getFolder("filepicker").getFile(fileName);

            if (fs.File.exists(file.path)) {
              folder.getFile("filepicker/" + fileName).remove()
            } else {
              console.log("not found")
            }
          }
        });
      }else{
        console.log("There was some problem to select the file. Looks like user has cancel it.")
      }

    })
    this.mediafilepicker.on("error", function (res: any) {
        console.log(res.msg)
    })
    this.mediafilepicker.startFilePicker(options);

thank you

**Comment by jibon57** [comment]
@dyazincahya 
`const Mediafilepicker = require("nativescript-mediafilepicker")`
instated of `import { Mediafilepicker, MediaFilepickerOptions } from 'nativescript-mediafilepicker';`

**Comment by dyazincahya** [comment]
### This is my code in JS

var Mediafilepicker = require("nativescript-mediafilepicker");
var mediafilepicker = new Mediafilepicker();

let MediaFilepickerOptions = {
        android: {
            mxcount: 2,
            enableImagePicker: true,
            enableVideoPicker: true,
            enableCameraSupport: true,
            pickFile: true,  
            addFileSupport: {
                title: "File",
                type: [".zip", ".rar", ".ZIP", ".pdf", ".doc", ".docx" ],
                icon: android.R.drawable.ic_dialog_info
            }
        },
        ios: {
            allowsMultipleSelection: true,
            title: "Album",
            showCameraButton: true,
        }
    };
    
    mediafilepicker.on("getFiles", function (res) {

        let files = res.files;

        if (files.length > 0) {

            files = files.split(",");

            files.forEach(file => {

                let fileName = file.replace(/^.*[\/]/, '');

                console.log(file);
                console.log(fileName);

                // you can do anything here


                if (app.ios) {

                    let folder = fs.knownFolders.documents();
                    let file = folder.getFolder("filepicker").getFile(fileName);

                    if (fs.File.exists(file.path)) {
                        folder.getFile("filepicker/" + fileName).remove()
                    } else {
                        console.log("not found")
                    }
                }
            });
        } else {
            console.log("There was some problem to select the file. Looks like user has cancel it.")
        }

    })
    mediafilepicker.on("error", function (res) {
        console.log(res.msg)
    })
    mediafilepicker.startFilePicker(MediaFilepickerOptions);


### But i have an error like this : 

An uncaught Exception occurred on "main" thread.
com.tns.NativeScriptException: 
Calling js method onViewAttachedToWindow failed

Error calling module function 

TypeError: Mediafilepicker is not a constructor
File: "file:///data/data/org.nativescript.pln/files/app/home/home-page.js, line: 5, column: 22

StackTrace: 
	Frame: function:'', file:'file:///data/data/org.nativescript.pln/files/app/home/home-page.js', line: 5, column: 23
	Frame: function:'require', file:'', line: 1, column: 266
	Frame: function:'_loop_1', file:'file:///data/data/org.nativescript.pln/files/app/tns_modules/tns-core-modules/globals/globals.js', line: 60, column: 22
	Frame: function:'global.loadModule', ...... .............. ...............etc.
