### ISSUE TITLE
Issue in android manifest file

### ISSUE THREAD

**Issue by haneef5k** [jibon57/nativescript-mediafilepicker#26]
13:37:24 - Compilation complete. Watching for file changes.

         + setting applicationId
         + applying user-defined configuration from C:\projects\Real_App\app\App_Resources\Android\app.gradle
         + adding nativescript runtime package dependency: nativescript-optimized-with-inspector
         + adding aar plugin dependency: C:\projects\Real_App\node_modules\nativescript-camera\platforms\android\nativescript_camera.aar
         + adding aar plugin dependency: C:\projects\Real_App\node_modules\nativescript-mediafilepicker\platforms\android\MultiTypeFilePicker-release.aar
         + adding aar plugin dependency: C:\projects\Real_App\node_modules\nativescript-mediafilepicker\platforms\android\nativescript_mediafilepicker.aar
         + adding aar plugin dependency: C:\projects\Real_App\node_modules\tns-core-modules-widgets\platforms\android\widgets-release.aar
C:\projects\Real_App\platforms\android\app\src\main\AndroidManifest.xml:19:17-55 Error:
        Attribute meta-data#android.support.FILE_PROVIDER_PATHS@resource value=(@xml/provider_paths) from [:nativescript_camera:] AndroidManifest.xml:19:17-55
        is also present at [:MultiTypeFilePicker-release:] AndroidManifest.xml:46:17-51 value=(@xml/file_paths).
        Suggestion: add 'tools:replace="android:resource"' to <meta-data> element at AndroidManifest.xml to override.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugManifest'.
> Manifest merger failed : Attribute meta-data#android.support.FILE_PROVIDER_PATHS@resource value=(@xml/provider_paths) from [:nativescript_camera:] AndroidManifest.xml:19:17-55
        is also present at [:MultiTypeFilePicker-release:] AndroidManifest.xml:46:17-51 value=(@xml/file_paths).
       Suggestion: add 'tools:replace="android:resource"' to <meta-data> element at AndroidManifest.xml to override.

**Comment by haneef5k** [comment]
where i should place this exactly in manifest . 'tools:replace="android:resource"' ?

**Comment by nginx17** [comment]
Please reopen this issue , cause not fixed the problem

**Comment by jibon57** [comment]
@haneef5k Please follow this one: https://stackoverflow.com/a/45025597/8875176

also remove `nativescript-camera` because this plugin is conflict here. 

@nginx17 this problem isn't related with this plugin.

**Comment by jibon57** [comment]
@haneef5k if you are following https://stackoverflow.com/a/45025597/8875176 then you may need to change 

`details.useVersion '25.3.0'` to `details.useVersion '27.0.1'`

**Comment by jibon57** [comment]
@nginx17, thank you! I am closing this issue.

**Comment by haneef5k** [comment]
Thank you @nginx17  and @jibon57

**Comment by nginx17** [comment]
@all 

If you use the solution above, it only removes errors during run / bundle. but when using nativescript-camera you will find new problems and I haven't found a solution to use these 2 plugins at once.

**Comment by hariaravind10** [comment]
------------------------
1. add this in manifest.xml
------------------------
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
	package="__PACKAGE__"
	android:versionCode="14"
	android:versionName="1.0.14"
	xmlns:tools="http://schemas.android.com/tools">

------------------------
2. add this 
------------------------
        <provider
            android:name="android.support.v4.content.FileProvider"
            android:authorities="${applicationId}.provider"
            android:exported="false"
            android:grantUriPermissions="true"
			tools:replace="android:authorities">
            <meta-data
                android:name="android.support.FILE_PROVIDER_PATHS"
                android:resource="@xml/file_paths" 
				tools:replace="android:resource"/>
        </provider>
	</application>
</manifest>

it worked for me

**Comment by diegovincent** [comment]
FYI See: https://github.com/jibon57/nativescript-mediafilepicker/issues/33

**Comment by csimpi** [comment]
These are not working for me
`Manifest merger failed : Attribute meta-data#android.support.FILE_PROVIDER_PATHS@resource value=(@xml/provider_paths) from AndroidManifest.xml:54:11-45
        is also present at [:nativescript_mediafilepicker:] AndroidManifest.xml:46:17-51 value=(@xml/file_paths).
        Suggestion: add 'tools:replace="android:resource"' to <meta-data> element at AndroidManifest.xml to override.
`

AndroidManifest

```
		<activity
			android:name="com.tns.NativeScriptActivity"
			android:label="@string/title_activity_kimera"
			android:configChanges="keyboard|keyboardHidden|orientation|screenSize|smallestScreenSize|screenLayout|locale|uiMode"
      android:launchMode="singleTask"
      android:hardwareAccelerated="true"
      android:windowSoftInputMode="stateHidden|adjustResize"
			android:theme="@style/LaunchScreenTheme">

			<meta-data android:name="SET_THEME_ON_LAUNCH" android:resource="@style/AppTheme" />
      <meta-data android:name="com.facebook.sdk.ApplicationId" android:value="@string/facebook_app_id"/>
      <provider android:authorities="com.facebook.app.FacebookContentProviderXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
                android:name="com.facebook.FacebookContentProvider"
                android:exported="true"
                tools:replace="android:authorities"/>

      <provider
        android:name="android.support.v4.content.FileProvider"
        android:authorities="${applicationId}.provider"
        android:exported="false"
        android:grantUriPermissions="true"
        tools:replace="android:authorities">
        <meta-data
          android:name="android.support.FILE_PROVIDER_PATHS"
          android:resource="@xml/file_paths"
          tools:replace="android:resource"/>
      </provider>
```
