### ISSUE TITLE
{N} + A build android error 

### ISSUE THREAD

**Issue by nginx17** [jibon57/nativescript-mediafilepicker#27]
Hi @jibon57 
I have an error when the Android build is as follows:

> ERROR in node_modules/nativescript-mediafilepicker/index.d.ts(9,40): error TS2304: Cannot find name 'PHAsset'.
node_modules/nativescript-mediafilepicker/index.d.ts(10,38): error TS2304: Cannot find name 'AVURLAsset'.
node_modules/nativescript-mediafilepicker/index.d.ts(11,38): error TS2304: Cannot find name 'PHAsset'.
node_modules/nativescript-mediafilepicker/index.d.ts(12,38): error TS2304: Cannot find name 'UIImage'.

TNS Info

> ✔ Getting NativeScript components versions information...
✔ Component nativescript has 4.2.3 version and is up to date.
✔ Component tns-core-modules has 4.2.0 version and is up to date.
✔ Component tns-android has 4.2.0 version and is up to date.
✖ Component tns-ios is not installed.

nativescript-mediafilepicker version 2.0.5

**Comment by jibon57** [comment]
@nginx17, thanks for pointing out it. You faced problem because you didn't have `tns-platform-declarations` installed. Give a try new version.

```
tns plugin remove nativescript-mediafilepicker
tns plugin add nativescript-mediafilepicker
tns platform remove android 
tns build android
```
