### ISSUE TITLE
nullpointerException while scrolling file picker folders

### ISSUE THREAD

**Issue by Sumit-ignistec** [jibon57/nativescript-mediafilepicker#3]
Hi, While scrolling folder from filepicker on android get null pointer and app creshes, Is there any configuration for this

System.err: java.lang.NullPointerException
System.err:     at java.io.File.<init>(File.java:262)
System.err:     at droidninja.filepicker.adapters.FolderGridAdapter.onBindViewHolder(FolderGridAdapter.java:71)
System.err:     at droidninja.filepicker.adapters.FolderGridAdapter.onBindViewHolder(FolderGridAdapter.java:24)

**Comment by jibon57** [comment]
Hi,

Will you please share your JS code here? Looks like this problem is related with library. In this case I mayn’t help you. :( 

Thanks

**Comment by jibon57** [comment]
No further response so closing it.
