### ISSUE TITLE
Manifest merger failed (Android)

### ISSUE THREAD

**Issue by bachras** [jibon57/nativescript-mediafilepicker#30]
Hi,

Thanks for new plugin update. I just updated to the latest version and here is the problem I get when I try to run the app(Android):
````
* What went wrong:
Execution failed for task ':app:processDebugManifest'.
> Manifest merger failed : Attribute meta-data#android.support.FILE_PROVIDER_PATHS@resource value=(@xml/provider_paths) from [:nativescript_camera:] AndroidManifest.xml:19:17-55
        is also present at [:MultiTypeFilePicker-release:] AndroidManifest.xml:46:17-51 value=(@xml/file_paths).
        Suggestion: add 'tools:replace="android:resource"' to <meta-data> element at AndroidManifest.xml to override.
`````
Any ideas how to solve it?

**Comment by jibon57** [comment]
You will need to uninstall `nativescript-camera` plugin. Here more: https://github.com/jibon57/nativescript-mediafilepicker/issues/26#issuecomment-419879726

**Comment by bachras** [comment]
If I uninstall nativescript-camera plugin, then it has a problem with social-share plugin.

**Comment by jibon57** [comment]
In this case you will can try to adjust the values in you `AndroidManifest.xml` & remove from plugins but I ain't 100% sure about it.
