### ISSUE TITLE
What is happening???

### ISSUE THREAD

**Issue by baretka** [jibon57/nativescript-mediafilepicker#36]
OS: IOS
Version: last(12/10/2018)
Problem:
mediafilepicker.openImagePicker(options); opens video picker not image picker
mediafilepicker.openVideoPicker(options); opens audio picker not video picker
mediafilepicker.openAudioPicker(options); opens...nothing(white screen)

This picker is terrible what is going on?

code:
 var options: ImagePickerOptions = {
                android: {
                    isNeedCamera: true,
                    maxNumberFiles: 10,
                    isNeedFolderList: true
                },
                ios: {
                    isCaptureMood: false,
                    maxNumberFiles: 10
                }
            };

  mediafilepicker.openImagePicker(options);

**Comment by jibon57** [comment]
https://github.com/jibon57/nativescript-mediafilepicker/issues/32
