### ISSUE TITLE
[Ask] access direct to camera without image list

### ISSUE THREAD

**Issue by nginx17** [jibon57/nativescript-mediafilepicker#37]
@jibon I know if this plugin is installed along with the camera plugin it will cause unresolved problems and must choose one of the 2 plugins (this or camera).

How can I directly access the camera without having to go through the list of images first? if I change the value of `isNeedFolderList` to` false` there is no impact whatsoever, it still has to go through the list of images.

Thank you in advance

**Comment by jibon57** [comment]
@nginx17 No sorry. The native library of Android doesn't support that.

**Comment by jibon57** [comment]
@nginx17 will you please try this branch : https://github.com/jibon57/nativescript-mediafilepicker/tree/direct-capture
I did custom implementation for Android. Check the demo project.

**Comment by nginx17** [comment]
@jibon, your demo works perfectly and like what I expect, please merge it as soon as possible because I'm sure this will be a solution for other users who use the camera plugin.

cheers

**Comment by jibon57** [comment]
@nginx17 try the latest version `tns plugin add nativescript-mediafilepicker@latest`

**Comment by nginx17** [comment]
thank you @jibon57
