### ISSUE TITLE
Cannot read property 'AudioPickActivity' of undefined

### ISSUE THREAD

**Issue by marojusantosh** [jibon57/nativescript-mediafilepicker#38]
I am getting this following error before the app is synced:
System.err: TypeError: Cannot read property 'AudioPickActivity' of undefined
System.err: File: "file:///data/data/org.nativescript.mytypescriptTemplate/files/app/tns_modules/nativescript-mediafilepicker/mediafilepicker.js, line: 6, column: 56

Should I add any tag in AndroidManifest.xml for 'com.vincent.filepicker.activity.AudioPickActivity'

Please help.

Thanks in advance

**Comment by jibon57** [comment]
```
tns platform remove android
tns prepare android
tns run android
```

**Comment by marojusantosh** [comment]
Thank you, it worked.
