### ISSUE TITLE
Demo directory: npm error code EWINDOWSPATH

### ISSUE THREAD

**Issue by lin-brian-l** [jibon57/nativescript-mediafilepicker#4]
I'm using a Mac and tried to download the repo to demo it, but when I tried doing "tns platform add android" in the demo directory, I got an error saying "Can't install from windows path on a non-windows system: D:\Others\Documents\My_Works\testing\nativescript-mediafilepicker\src". The same error happens when I try running "npm install" to get a node_modules folder.

**Comment by jibon57** [comment]
@lin-brian-l You will need to run command inside `src` directory. Try like this

```
npm install 
npm run clean
npm run demo.reset
npm run demo.android
npm run demo.ios
```

**Comment by lin-brian-l** [comment]
Thanks!
