### ISSUE TITLE
videopicker fails in IOS

### ISSUE THREAD

**Issue by odparraj** [jibon57/nativescript-mediafilepicker#40]
**Describe the bug**
it is a run-time error, I am trying to get a video using the  plugin, it turns out that in the execution when I select the video sometimes an error is generated that blocks the application.

**To Reproduce**

launch the video file picker and select a video from the gallery, it does not always happen but surely if you do it 5 times repetitively you will find the error.

**Expected behavior**
get video information

**NativeScript Info(please run `tns info`):**

CLI: 4.2.0
Cross-platform modules: 4.2.0
Android Runtime: 4.2.0
iOS Runtime: 4.2.0
Plugin(s): nativescript-mediafilepicker: 2.0.13

**Sample Code(please provide minimum code to reproduce problem):**
your demo

**Additional context**
The error only happens in ios, I'm testing in ios 12, it happens in a physical device because in the emulator it works well although sometimes it does not return file, the failure is given with some videos, sometimes it works and sometimes it does not.

attached an image of the errors that throws

![captura de pantalla 2018-10-16 a la s 8 29 59 a m](https://user-images.githubusercontent.com/9358581/46898425-43cc4980-ce4f-11e8-9606-3473a00fb8d6.png)

**Comment by jibon57** [comment]
Are you selecting icloud files? If so then you will get hard crash.

**Comment by odparraj** [comment]
I've been stuck in this error for a while, in fact I had to migrate all my application to add support to the latest version of your plugin because I did not find a solution, but the problem was not solved, if it has to do with the icloud files there any solution

**Comment by odparraj** [comment]
log icloud in the emulator and launch the picker does not show icloud files only the local files, I would believe that it is not the error

**Comment by jibon57** [comment]
Please check the limitation section from the plugin. Selection of icloud file isn't supported by native library. So, this plugin won't work as well as.

**Comment by Suralal001** [comment]
Is it possible to add an exception for the crash which was caused once we select a video from icloud
