### ISSUE TITLE
Choose Folder

### ISSUE THREAD

**Issue by coderaven** [jibon57/nativescript-mediafilepicker#42]
There are cases in which an app lets user choose a folder (for saving, storing, etc.).
Can we have the plugin to support this - or is it currently supported?

**Comment by jibon57** [comment]
No, sorry. This plugin doesn't have such feature but pull requests are always welcome :)

**Comment by aleksander351** [comment]
Yes, how could we implement folder selection dropdown for openFilePicker, like for all the other methods.

 Why is there "isNeedFolderList: true" for all methods, except for openFilePicker?
