### ISSUE TITLE
Settimeout on handleResults

### ISSUE THREAD

**Issue by SkupeZZ** [jibon57/nativescript-mediafilepicker#44]
First and foremost, thanks for this amazing plugin! It worked great at the first try, but I noticed there is a small delay on **android** after I select videos, images, etc. So I was reading the source code and noticed that there is a settimeout on handleResults (Mediafilepicker class) which delays results by 1 second. I was wondering if there is a reason for this?

**Comment by jibon57** [comment]
If we don't do that delay then there may have chances to get crash.
