### ISSUE TITLE
Mediafilepicker doesn't open behind modal dialog in iOS

### ISSUE THREAD

**Issue by bachras** [jibon57/nativescript-mediafilepicker#5]
Thank you for brilliant plugin. It perfectly fine, but when I try to open file selection from modal dialog on iOS it is not opening or opening behind modal dialog and I can't see it. It works fine from main page. Is there any workaround for this problem? 

P.s. Android works fine  from modal dialog as well as main page.

Any suggestion are highly appreciated. Thank you

**Comment by jibon57** [comment]
@bachras Sorry, don't have idea to resolve this. iOS works differently then Android.

**Comment by jibon57** [comment]
try new version
