### ISSUE TITLE
other android picker

### ISSUE THREAD

**Issue by wendt88** [jibon57/nativescript-mediafilepicker#50]
thanks for your awesome plugin!
I noticed on android a lag between closing the picker (by canceling or selecting files) and the `getFiles` event.
I tried also the imagepicker plugin from the nativescript market: https://github.com/NativeScript/nativescript-imagepicker
It seems more fluent.
I'm not good in native android and wasn't able to extend the imagepicker to pick multiple filetypes (only any or a certain mime type group -> https://github.com/NativeScript/nativescript-imagepicker/blob/master/src/imagepicker.android.ts#L197).

So my question is: Is it possible to use this kind of picker for android instead the https://github.com/fishwjy/MultiType-FilePicker?

**Comment by jibon57** [comment]
So my question is: Is it possible to use this kind of picker for android instead the https://github.com/fishwjy/MultiType-FilePicker?
> Of course it's possible but I don't have any plan to do that. You are welcome to develop your own implementation.
