### ISSUE TITLE
How to ask user only image permission

### ISSUE THREAD

**Issue by diadal** [jibon57/nativescript-mediafilepicker#53]
is there any way to access image and disable Audio & Video also how to override the default permission text

**Comment by jibon57** [comment]
Your question wasn't clear to me. You can use image picker only for allowing user to pickup image. For changing text you will need to customization here:

https://github.com/jibon57/nativescript-mediafilepicker/blob/eea3d3c1d2323a75a4c84e598bfcf4932fd101af/src/mediafilepicker.android.ts#L163

https://github.com/jibon57/nativescript-mediafilepicker/blob/eea3d3c1d2323a75a4c84e598bfcf4932fd101af/src/mediafilepicker.android.ts#L281

**Comment by diadal** [comment]
I use this at the moment https://developer.apple.com/library/archive/qa/qa1937/_index.html
