### ISSUE TITLE
On Image capture mode plugin increases the selection count more than one

### ISSUE THREAD

**Issue by mayureshjadhav** [jibon57/nativescript-mediafilepicker#54]
**Describe the bug**
On image capture mode plugin returning more than one image file path

**To Reproduce**
Step 1 - Open an image picker 
Step 2 - Click on the Image capture button
Step 3 - After capturing an image count for selection of image gets increases

**Expected behavior**
If I am capturing an image, then it should only show one image as a selection not more than one

**Comment by jibon57** [comment]
You haven't shared any code. Have you checked it https://github.com/jibon57/nativescript-mediafilepicker/issues/35
