### ISSUE TITLE
Video not Uploading in ios

### ISSUE THREAD

**Issue by Mubashir-Mohamed** [jibon57/nativescript-mediafilepicker#55]
Platform : IOS

Nativescript+Angular

I selected a video. the video is moved to the application folder. but when i am uploading the video to server , I am getting bad request
error: 

"errors": [
    {
      "code": "400",
      "message": "Image size must be greater than 1024 bytes",
      "field": "signMedia"
    }
  ]

Thanks in advance

**Comment by jibon57** [comment]
You didn't follow issue template to provide necessary info

**Comment by Mubashir-Mohamed** [comment]
Describe the bug
On iOS , when we get the path of the selected video file, and try to upload it to the server . It shows that it is empty file or there is no file . 
error showing:
errors": [
{
"code": "400",
"message": "Image size must be greater than 1024 bytes",
"field": "signMedia"
}
]


To Reproduce
Just add Nativescript mediafilepicker plugin in a sample app and select a video any try uploading to a server

Expected behavior
The video should be uploaded to the server. Its working perfectly in android. But not in Ios

NativeScript Info(please run tns info):
Component nativescript has 4.2.4 version and is up to date.
✔ Component tns-core-modules has 4.3.0-2018-09-07-01 version and is up to date.
✔ Component tns-ios has 4.2.0  version
