### ISSUE TITLE
Disabled the target

### ISSUE THREAD

**Issue by NeriCodec** [jibon57/nativescript-mediafilepicker#57]
If there are several plugins with a goal, it is impossible to compile this plugin

In line: https://github.com/jibon57/nativescript-mediafilepicker/blob/eea3d3c1d2323a75a4c84e598bfcf4932fd101af/src/platforms/ios/Podfile#L1

**Comment by jibon57** [comment]
@NeriCodec from NativeScript `5.2.0` this problem will be solved. 
ref: https://github.com/NativeScript/nativescript-cli/pull/4332
