### ISSUE TITLE
Select video

### ISSUE THREAD

**Issue by srcarmi** [jibon57/nativescript-mediafilepicker#58]
**Describe the bug**
Error select Video

**To Reproduce**
***** Fatal JavaScript exception - application has been terminated. *****
Native stack trace:
1   0x10f82bd3b NativeScript::reportFatalErrorBeforeShutdown(JSC::ExecState*, JSC::Exception*, bool, bool)
2   0x10f83cdb1 NativeScript::FFICallback<NativeScript::ObjCBlockCallback>::ffiClosureCallback(ffi_cif*, void*, void**, void*)
3   0x110176656 ffi_closure_unix64_inner
4   0x11017707a ffi_closure_unix64
5   0x11e83dc5f __64-[PHImageManager _requestAVAssetForAsset:options:resultHandler:]_block_invoke
6   0x11e83c68f __100-[PHImageManager _requestAsynchronousVideoURLForAsset:chainedToMasterRequest:options:resultHandler:]_block_invoke.1358
7   0x11e837060 __48-[PHCoreImageManager _processImageRequest:sync:]_block_invoke.1073
8   0x11e834dff __134-[PHCoreImageManager _fetchAdjustmentDataThruAssetsdAndCPLHandlerWithRequest:networkAccessAllowed:trackCPLDownload:completionHandler:]_block_invoke
9   0x12280000b __111-[PLGatekeeperClient requestAdjustmentDataForAsset:withDataBlob:networkAccessAllowed:trackCPLDownload:handler:]_block_invoke
10  0x112d513b2 _xpc_connection_reply_callout
11  0x112d466e0 _xpc_connection_call_reply_async
12  0x11292076b _dispatch_client_callout3
13  0x1129353ee _dispatch_mach_msg_async_reply_invoke
14  0x1129250fa _dispatch_queue_override_invoke
15  0x11292ac88 _dispatch_root_queue_drain
16  0x11292aa51 _dispatch_worker_thread3
17  0x112e43169 _pthread_wqthread
18  0x112e42be9 start_wqthread
JavaScript stack trace:
1   @file:///app/tns_modules/nativescript-mediafilepicker/mediafilepicker.js:334:37
2   UIApplicationMain@[native code]
3   start@file:///app/tns_modules/tns-core-modules/application/application.js:264:26
4   run@file:///app/tns_modules/tns-core-modules/application/application.js:284:10
5   bootstrapNativeScriptApp@file:///app/tns_modules/nativescript-angular/platform-common.js:157:26
6   bootstrapApp@file:///app/tns_modules/nativescript-angular/platform-common.js:91:38
7   bootstrapModule@file:///app/tns_modules/nativescript-angular/platform-common.js:80:26
8   anonymous@file:///app/main.js:7:57
9   evaluate@[native code]
10  moduleEvaluation@[native code]
11  promiseReactionJob@[native code]
JavaScript error:
file:///app/tns_modules/nativescript-mediafilepicker/mediafilepicker.js:334:37: JS ERROR TypeError: null is not anobject (evaluating 'urlAsset.URL')

**Expected behavior**

**NativeScript Info(please run `tns info`):**

**Sample Code(please provide minimum code to reproduce problem):**
 let allowedVideoQualities = [];

          if (isIOS) {
            allowedVideoQualities = [
              AVCaptureSessionPreset1920x1080,
              AVCaptureSessionPresetHigh
            ]; // get more from here: https://developer.apple.com/documentation/avfoundation/avcapturesessionpreset?language=objc
          }

          let options: VideoPickerOptions = {
            android: {
              isCaptureMood: false, // if true then camera will open directly.
              isNeedCamera: true,
              maxNumberFiles: 2,
              isNeedFolderList: true,
              maxDuration: 20
            },
            ios: {
              isCaptureMood: false, // if true then camera will open directly.
              videoMaximumDuration: 10,
              allowedVideoQualities: allowedVideoQualities
            }
          };
          let mediafilepicker = new Mediafilepicker();
          mediafilepicker.openVideoPicker(options);

          mediafilepicker.on("getFiles", function(res) {
            setTimeout(() => {
              let results = res.object.get('results');

              console.log(results)
            },1000)

**Additional context**

**Comment by jibon57** [comment]
Are you selecting iCloud videos? You will get error if you will iCloud videos.

**Comment by srcarmi** [comment]
Yes, Solutions?
