### ISSUE TITLE
maxNumberFiles not working

### ISSUE THREAD

**Issue by HugoAntares** [jibon57/nativescript-mediafilepicker#59]
**The bug**
I set `maxNumberFiles: 1` and the user can select multiple images, and the `getFiles` callback has multiple images.

**Expected behavior**
The user can only select 1 image and the `res.object.get('results');` should only contains 1 element.

**NativeScript Info**
✔ Getting NativeScript components versions information...
✔ Component nativescript has 5.2.0 version and is up to date.
✔ Component tns-core-modules has 5.2.1 version and is up to date.
⚠ Update available for component tns-android. Your current version is 5.0.0 and the latest available version is 5.2.1.
⚠ Update available for component tns-ios. Your current version is 5.0.0 and the latest available version is 5.2.0.

**Sample Code**
```typescript
const options = {
    android: {
        isCaptureMood: false, // if true then camera will open directly.
        isNeedCamera: true,
        maxNumberFiles: 1,
        isNeedFolderList: true,
    },
    ios: {
        isCaptureMood: false, // if true then camera will open directly.
        maxNumberFiles: 1,
    },
};

const mediafilepicker = new Mediafilepicker();
mediafilepicker.openImagePicker(options);
            
mediafilepicker.on('getFiles', (res) => {
    const results = res.object.get('results');
    console.dir(results); // results has multiple files
});
```

**Comment by jibon57** [comment]
@HugoAntares iOS has this limitation because of native library problem. At present no solution.
