### ISSUE TITLE
getFiles() in iOS sometimes is not fired every time

### ISSUE THREAD

**Issue by relez** [jibon57/nativescript-mediafilepicker#60]
Hi there, I am trying use this great plugin in my apps and I found out that sometimes the getFiles event is not fire very time. I have played with the plugin and try to shot some pictures and select one and not always is fired. Can you look into it? I have created a sample app on github.

[https://github.com/relez/ns-photo-ng.git](https://github.com/relez/ns-photo-ng.git)

Here is the code I am using:

```
let options: ImagePickerOptions = {
    android: {
        isCaptureMood: true, // if true then camera will open directly.
        isNeedCamera: true,
        maxNumberFiles: 1,
        isNeedFolderList: true
    }, ios: {
        isCaptureMood: true, // if true then camera will open directly.
        maxNumberFiles: 1
    }
};

let mediafilepicker = new Mediafilepicker();
mediafilepicker.openImagePicker(options);
                    
mediafilepicker.on("getFiles", function (res) {
    console.log('getFiles');
});
                    
mediafilepicker.on("error", function (res) {
});
                    
mediafilepicker.on("cancel", function (res) {
});
```

Thanks!

**Comment by jibon57** [comment]
This will happen if you will select icloud files.

**Comment by joralegre** [comment]
Same problem here. Really weird.
Sometimes, if I select one file, it doesn't fire the "getfiles". If I try again, and select the same file it does fire the "getfiles"... Can occur using camera files, screenshots, random images (jpg, png or heic files..)
Right now I have iCloud images sync disabled, I've take a new photo using camera and it still happens... 
any idea?

**Comment by Naxos84** [comment]
Also happens on the iOS Simulator for IPhone6 (12.2) (There are only 6 example images)

**Comment by lucasumberto** [comment]
Hello, Im having the same problem, only when `isCaptureMood: true`
if I select from the gallery it is ok, but if I took a picture with the camera it will fail most of the times...

acessarCamera is true or false according to the captureMood

```
let options = {
                    android: {
                        isCaptureMood: acessarCamera,
                        isNeedCamera: true,
                        maxNumberFiles: 10,
                        isNeedFolderList: true
                    }, ios: {
                        isCaptureMood: acessarCamera,
                        isNeedCamera: true,
                        maxNumberFiles: 10
                    }
                };

                let mediafilepicker = new Mediafilepicker();
                mediafilepicker.openImagePicker(options);
                console.log("1");

                mediafilepicker.on("getFiles", (res) => {
                    console.log("2", res.object.get('results'));
                });
```

{
  "nativescript": {
    "id": "org.nativescript.ceonapp",
    "tns-android": {
      "version": "6.5.0"
    },
    "tns-ios": {
      "version": "6.5.0"
    }
  },
  "description": "",
  "license": "SEE LICENSE IN <your-license-filename>",
  "repository": "<fill-your-repository-here>",
  "dependencies": {
    "@nativescript/theme": "^2.3.0-2020-01-13-101337-01",
    "@nstudio/nativescript-checkbox": "^1.0.0",
    "axios": "^0.19.1",
    "moment": "^2.24.0",
    "nativescript-input-mask": "^1.0.5",
    "nativescript-iqkeyboardmanager": "^1.5.1",
    "nativescript-mediafilepicker": "^3.0.1",
    "nativescript-secure-storage": "^2.6.0",
    "nativescript-statusbar": "^5.0.0",
    "nativescript-ui-calendar": "^6.0.0",
    "nativescript-ui-sidedrawer": "^8.0.0",
    "nativescript-vue": "~2.4.0",
    "tns-core-modules": "~6.5.0",
    "vuex": "^3.1.2"
  },
  "devDependencies": {
    "@babel/core": "~7.1.0",
    "@babel/preset-env": "~7.1.0",
    "babel-loader": "~8.0.0",
    "nativescript-dev-webpack": "~1.5.0",
    "nativescript-vue-template-compiler": "~2.4.0",
    "node-sass": "^4.14.1",
    "vue-loader": "~15.4.0"
  },
  "gitHead": "",
  "readme": "NativeScript Application",
  "author": ""
}

**Comment by Stanteq** [comment]
I have the same problem, is not fired.
