### ISSUE TITLE
[Question] how "Custom File Picker" work in iOS

### ISSUE THREAD

**Issue by marcuschoong** [jibon57/nativescript-mediafilepicker#61]
Thanks for the awesome library, I implemented "Custom file picker" and its work fine in android platform with the demo code.

> let extensions = [];
> 
> if (app.ios) {
>     extensions = [kUTTypePDF, kUTTypeText]; // you can get more types from here: https://developer.apple.com/documentation/mobilecoreservices/uttype
> } else {
>     extensions = ['txt', 'pdf'];
> }
> 
> let options: FilePickerOptions = {
>     android: {
>         extensions: extensions,
>         maxNumberFiles: 2
>     },
>     ios: {
>         extensions: extensions,
>         multipleSelection: true
>     }
> };
> 
> let mediafilepicker = new Mediafilepicker(); 
> mediafilepicker.openFilePicker(options);
> 
> mediafilepicker.on("getFiles", function (res) {
>     let results = res.object.get('results');
>     console.dir(results);
> });
> 
> mediafilepicker.on("error", function (res) {
>     let msg = res.object.get('msg');
>     console.log(msg);
> });
> 
> mediafilepicker.on("cancel", function (res) {
>     let msg = res.object.get('msg');
>     console.log(msg);
> });

However when I test with iOS, picker only available to display iCloud file and the file is not selectable. I notice that you are stated the in the limitation that iCloud is not supported. 

So may I know what is the usage for pick file in iOS? how can I attached file in iOS platform ?

**Comment by jibon57** [comment]
@marcuschoong if you are using custom file picker in iOS then this limitation won't be applicable because I have used `UIDocumentPickerViewController` which will copy iCloud file temporary to your app directory.

**Comment by marcuschoong** [comment]
@jibon57 since the iCould file has temporary copy to the app directory, do you have any plan to open the file in iOS in the future release ?

**Comment by jibon57** [comment]
@marcuschoong the purpose of this plugin isn't to open a file. For opening file you will have to use different extensions.

**Comment by harshitjain0803** [comment]
Hi,
When i use custom file picker... i get an error as 'NSErrorWrapper: You don’t have permission to save the file “com.appid-Inbox” in the folder “tmp”.'
Can you please help me with the same?

**Comment by tralves** [comment]
@harshitjain0803 see my solution here: https://github.com/jibon57/nativescript-mediafilepicker/issues/103#issuecomment-694159938
