### ISSUE TITLE
videoMaximumDuration is not working in IOS

### ISSUE THREAD

**Issue by Mubashir-Mohamed** [jibon57/nativescript-mediafilepicker#62]
**Describe the BUG**
videoMaxDuration property is not working as intended in IOS

**Steps to reproduce**

Implement the plugin with this property. and try to select video which has more seconds than mentioned.

**Current behaviour**
if we mention    _videoMaximumDuration: 10,_ , if we select video which has more than 10 seconds is also able to select.

**Expected Behaviour**

Videos having lessthan or equal to 10 seconds must only be able to be picked.

**Comment by jibon57** [comment]
@Mubashir-Mohamed no, that option isn't for selecting video that has 10 seconds. It's for recording limit using this plugin.

**Comment by Mubashir-Mohamed** [comment]
@jibon57  So we cant limit the size of the video taken from the gallery?

**Comment by jibon57** [comment]
With this plugin at present not possible. But you can check the file size as soon as user will pickup then can give warning that the size of the file has been exceeded the limit. That's the only work around is possible now.
