### ISSUE TITLE
App crashes when video is selected from icloud in ios

### ISSUE THREAD

**Issue by Suralal001** [jibon57/nativescript-mediafilepicker#65]
When selecting upload from gallery and when clicking on video which is from cloud the app crashes in ios

The plugin doesn't support fetching icloud videos.is it possible to catch the exception and show a message.

**Comment by jibon57** [comment]
You can use try catch exception like this:
```
.....
let mediafilepicker = new Mediafilepicker();
try {
  mediafilepicker.openImagePicker(options);
}
catch (e) {
  alert(JSON.stringify(e));
}
```
