### ISSUE TITLE
[Question] Custom File Picker iOS not able to copy pdf file to app directory.

### ISSUE THREAD

**Issue by pradumnk-mahanta** [jibon57/nativescript-mediafilepicker#67]
**Question**
First of all this is a great extension and combines all the file operations possible. I have been exploring the demo project and came across one issue that I could not find an answer to even after researching for hours. I used the custom file picker and then selected a PDF. Tried to copy it to app directory in iOS using all the available methods.

`// iOS only'
'copyPHImageToAppDirectory(rawData: PHAsset, fileName: any): Promise<{}>;
copyPHVideoToAppDirectory(asset: AVURLAsset, fileName: any): Promise<{}>;
convertPHImageToUIImage(rawData: PHAsset): Promise<{}>;
copyUIImageToAppDirectory(image: UIImage, fileName: any): Promise<{}>;
copyMPMediaFileToAPPDirectory(mediaItem: MPMediaItem, filename: any): Promise<{}>;    `

**Expected behavior**
The file should have got copied with the available methods.

**Error Log**
`CONSOLE LOG file:///app/main-view-model.js:198:24:
==== object dump start ====
0: {
"type": "normalFile",
"file": "file:///private/var/mobile/Containers/Data/Application/F229F04A-F676-4614-8DCB-C39BE2270E7A/tmp/org.ymsli.demopicker-Inbox/20131231103232738561744.pdf",
"rawData": {}
}
==== object dump end ====
CONSOLE LOG file:///app/main-view-model.js:204:32: file:///private/var/mobile/Containers/Data/Application/F229F04A-F676-4614-8DCB-C39BE2270E7A/tmp/org.ymsli.demopicker-Inbox/20131231103232738561744.pdf
CONSOLE LOG file:///app/main-view-model.js:205:32: -----------------------------------------------------------------------------------------------------------------------------1 20131231103232738561744.pdf`

Any help or pointers would be nice. Thank in advance.

**Comment by jibon57** [comment]
@pradumnk-mahanta the file has already been copied to your APP directory & you can use it for further work. But that file will be delete automatically after a while. If you would like to store it permanently then you can either upload it to remote server or in separate directory of your APP. You can have a look nativescript file-system for more details: https://docs.nativescript.org/ns-framework-modules/file-system

**Comment by pradumnk-mahanta** [comment]
<img width="1636" alt="Screenshot 2019-05-10 at 5 17 00 PM" src="https://user-images.githubusercontent.com/18536894/57525123-843d6880-7347-11e9-9720-b113440bb4a5.png">
Hi @jibon57  Please see attached. The demo application terminates with the following error.

**Comment by ibnYusrat** [comment]
> <img alt="Screenshot 2019-05-10 at 5 17 00 PM" width="1636" src="https://user-images.githubusercontent.com/18536894/57525123-843d6880-7347-11e9-9720-b113440bb4a5.png">
> 
> Hi @jibon57 Please see attached. The demo application terminates with the following error.

That is exactly what I am getting right now.. Were you able to find a solution to this?

**Comment by Shubhangvanjani** [comment]
> **Question**
> First of all this is a great extension and combines all the file operations possible. I have been exploring the demo project and came across one issue that I could not find an answer to even after researching for hours. I used the custom file picker and then selected a PDF. Tried to copy it to app directory in iOS using all the available methods.
> 
> `// iOS only' 'copyPHImageToAppDirectory(rawData: PHAsset, fileName: any): Promise<{}>; copyPHVideoToAppDirectory(asset: AVURLAsset, fileName: any): Promise<{}>; convertPHImageToUIImage(rawData: PHAsset): Promise<{}>; copyUIImageToAppDirectory(image: UIImage, fileName: any): Promise<{}>; copyMPMediaFileToAPPDirectory(mediaItem: MPMediaItem, filename: any): Promise<{}>; `
> 
> **Expected behavior**
> The file should have got copied with the available methods.
> 
> **Error Log**
> `CONSOLE LOG file:///app/main-view-model.js:198:24: ==== object dump start ==== 0: { "type": "normalFile", "file": "file:///private/var/mobile/Containers/Data/Application/F229F04A-F676-4614-8DCB-C39BE2270E7A/tmp/org.ymsli.demopicker-Inbox/20131231103232738561744.pdf", "rawData": {} } ==== object dump end ==== CONSOLE LOG file:///app/main-view-model.js:204:32: file:///private/var/mobile/Containers/Data/Application/F229F04A-F676-4614-8DCB-C39BE2270E7A/tmp/org.ymsli.demopicker-Inbox/20131231103232738561744.pdf CONSOLE LOG file:///app/main-view-model.js:205:32: -----------------------------------------------------------------------------------------------------------------------------1 20131231103232738561744.pdf`
> 
> Any help or pointers would be nice. Thank in advance.

@pradumnk-mahanta I am also facing the same issue in my application. Have you found any way to resolve this?

**Comment by pradumnk-mahanta** [comment]
@Shubhangvanjani Hey, this is because of the iOS File System limitations and also how the response is handled. Are you trying to pick an iCloud File? The latest version has already been implemented to handle this. But, at that time I implemented a custom service with native code to handle this issue for iOS. For the Android I used this plugin's picker.

**Comment by Shubhangvanjani** [comment]
Great @pradumnk-mahanta  !!! In the latest version i am going through the below issue. Can you give a little more brief that how can i resolve this ?

**Code Snippet**
mediafilepicker.on("getFiles", async function (res) {
                let results = res.object.get('results');
                console.log(">>>>>>>>>RESULTS>>", results)
                try{
                    let localStore = await mediafilepicker.copyMPMediaFileToAPPDirectory(results, name)
                }catch(err){
                    console.log("ERROR<<><>", err)
                }
}

**output**

CONSOLE LOG file:///app/bundle.js:1:233870: '>>>>>>>>>RESULTS>>' [ { type: 'normalFile',
    file: 'file:///private/var/mobile/Containers/Data/Application/F142712C-5B9A-4575-9A4B-86ECB30DA337/tmp/com.nativescript.salesforce-Inbox/test.pdf',
    rawData: {} },
  [length]: 1 
[TypeError: e.valueForProperty is not a function. (In 'e.valueForProperty(MPMediaItemPropertyAssetURL)', 'e.valueForProperty' is undefined)]

**Comment by pradumnk-mahanta** [comment]
@Shubhangvanjani, let me understand the requirement first, what do you want to do with the selected file? Upload it? Or Open It?

Because you can work forward with the path that you got, if the above are the cases. I can share my method of implementation, if you needed.

**Comment by Shubhangvanjani** [comment]
@pradumnk-mahanta I want to read the file and then convert it into base64 string after which i will upload that string to server. I had implemented this for android  and image upload with ios. If you can share your implementation it will be helpful as indirectly i want to upload file to server.

**Comment by jibon57** [comment]
@Shubhangvanjani why are you using `copyMPMediaFileToAPPDirectory` to copy `pdf` file? You should use [file-system](https://docs.nativescript.org/ns-framework-modules/file-system) to use for further processing. That file has been copied to `tmp` directory of your APP. So, you can have a look [knownfolders-methods](https://docs.nativescript.org/ns-framework-modules/file-system#knownfolders-methods).

**Comment by jibon57** [comment]
> I want to read the file and then convert it into base64 string

If you only want to encode in base64 then you can try like this way:

```
export function getBase64String(file) {
    const myFile: File = File.fromPath(file);
    const data = myFile.readSync();

    if (app.ios) {
        return data.base64EncodedStringWithOptions(0);
    }else if (app.android) {
        return android.util.Base64.encodeToString(data, android.util.Base64.NO_WRAP);
    }
}
```

**Comment by Shubhangvanjani** [comment]
> > I want to read the file and then convert it into base64 string
> 
> If you only want to encode in base64 then you can try like this way:
> 
> ```
> export function getBase64String(file) {
>     const myFile: File = File.fromPath(file);
>     const data = myFile.readSync();
> 
>     if (app.ios) {
>         return data.base64EncodedStringWithOptions(0);
>     }else if (app.android) {
>         return android.util.Base64.encodeToString(data, android.util.Base64.NO_WRAP);
>     }
> }
> ```

@jibon57  Yes i had implemented like this only in my case. For android its working but for ios File.fromPath(file) having some issue.

**Comment by Shubhangvanjani** [comment]
> @Shubhangvanjani, let me understand the requirement first, what do you want to do with the selected file? Upload it? Or Open It?
> 
> Because you can work forward with the path that you got, if the above are the cases. I can share my method of implementation, if you needed.

@pradumnk-mahanta can you share your method of implementation?

**Comment by kriefsacha** [comment]
@Shubhangvanjani File.fromPath is making me issues also on IOS, works fine on android.

You found a solution ?
