### ISSUE TITLE
Typescript Issue wrong maxNumberFiles typing

### ISSUE THREAD

**Issue by virtualbjorn** [jibon57/nativescript-mediafilepicker#68]
**Describe the bug**

Typing Bug located on mediafilepicker.common.d.ts

**To Reproduce**

The typing used is Number which is supposed to be number, on which is returns an error on runtime

**Expected behavior**

**NativeScript Info(please run `tns info`):**

**Sample Code(please provide minimum code to reproduce problem):**

**Additional context**

**Comment by jibon57** [comment]
This error can be avoided because as a plugin won't require that file.

**Comment by virtualbjorn** [comment]
I don't know why you closed it but the error is there and I can't build nor run it because it gives the error.

**Comment by jibon57** [comment]
Please write proper way with errors

**Comment by virtualbjorn** [comment]
Try making a new NativeScript-Angular project and use your documentation example on image picker.
I can't show you snippets rn. I'll upload them maybe later.

**Comment by virtualbjorn** [comment]
> This error can be avoided because as a plugin won't require that file.

Typescript reads the files as necessary

**Comment by virtualbjorn** [comment]
![image](https://user-images.githubusercontent.com/19782129/58086528-68607f00-7bf1-11e9-83b7-95d73de5ec7a.png)
Refer to the error above, manage to fix the problem by directly editing the interfaces inside the plugin

**Comment by virtualbjorn** [comment]
created a PR for the mentioned error above
https://github.com/jibon57/nativescript-mediafilepicker/pull/69

**Comment by virtualbjorn** [comment]
Any updates for this one?
