### ISSUE TITLE
Single file selector

### ISSUE THREAD

**Issue by ibnYusrat** [jibon57/nativescript-mediafilepicker#72]
Hi,

Thank you for the really nice plugin. I am sure if there is something missing in the documentation but I cannot find the option to allow user to select one file only. If I set `maxNumberFiles` to 1, it does allow selecting only one file, but the problem is the file picker is still in `multi file selection` mode. So the user cannot just tap a file to select it, they have to 'select' the file kind of like how they do when selecting multiple files.

Is this a limitation of Android/iOS or do you think something is missing here?

**Comment by jibon57** [comment]
As far I remember iOS has this problem. It's related with native library. Sorry, I won't be able to help here.
