### ISSUE TITLE
 TypeError: Cannot read property 'filepicker' of undefined

### ISSUE THREAD

**Issue by ann1111** [jibon57/nativescript-mediafilepicker#73]
TypeError: Cannot read property 'filepicker' of undefined error comes while using at angular nativescript please have a look and give me the suggestion .

https://play.nativescript.org/?template=play-ng&id=kM8Uhb&v=2

**Comment by virtualbjorn** [comment]
A couple of issues with typing. Did a cleanup on my PR.

**Comment by jibon57** [comment]
@ann11 you can't use this plugin in play. Try to clean platform directory in your local project. It should work.

**Comment by ann1111** [comment]
Same issue in local directory actually with angular it has issue

**Comment by FelipeVa** [comment]
I'm having this issue too
