### ISSUE TITLE
how to display the selected video

### ISSUE THREAD

**Issue by job111** [jibon57/nativescript-mediafilepicker#75]
whats the best way to display the selected video,,,i tried to use nativescript-videoplayer but wasnt able to display it

**Comment by virtualbjorn** [comment]
Hmm. Do you want to play the said video in-app?

**Comment by job111** [comment]
am using nativescript-mediafilepicker to pick a video from the gallery ,,,,but what i cant get my head around is how to display on the app ,,,,tried to do it by setting a variable but failed

**Comment by virtualbjorn** [comment]
Each platform have its own handling for these type of files. On Android Image i used its file path to show the image while on iOS used its rawdata/PHAsset to get the image and show it on the app.

**Comment by job111** [comment]
yes i get that ...what about displaying a video

**Comment by jibon57** [comment]
@job111 you will have to find way to display video. You can do native implementation as NativeScript support to implement native implementation easily. From this plugin you will get files information only. For further processing will depends on you

**Comment by job111** [comment]
@jibon57  alright will work on that

**Comment by job111** [comment]
this is what i tried on displaying the video
`import { Component, OnInit, ViewChild, ElementRef} from "@angular/core";
import { RadSideDrawer } from "nativescript-ui-sidedrawer";
import * as app from "tns-core-modules/application";
import { Page } from "tns-core-modules/ui/page";



import * as fs from 'tns-core-modules/file-system';

import { registerElement } from "nativescript-angular/element-registry";
import { Video } from 'nativescript-videoplayer';
registerElement("VideoPlayer", () => Video);
import { Mediafilepicker, ImagePickerOptions, VideoPickerOptions, AudioPickerOptions, FilePickerOptions } from 'nativescript-mediafilepicker';
import { findTopActivatedRouteNodeForOutlet } from "nativescript-angular/router/page-router-outlet";
@Component({
    selector: "Home",
    moduleId: module.id,
    templateUrl: "./home.component.html"
})
export class HomeComponent implements OnInit {
    videoPlayer: any;
    setNativeSource: boolean
    public videoSrc:string;
    constructor(private page: Page) {
        // Use the component constructor to inject providers.
    }

    ngOnInit(): void {
        // Init your component properties here.
    }
    ngAfterViewInit() {
        this.videoPlayer = this.page.getViewById('nativeVideoPlayer');
    }

   show():void{


    let options: VideoPickerOptions = {

        android: {

            isCaptureMood: false,

            isNeedCamera: true,

            maxNumberFiles: 2,

            isNeedFolderList: true,

            maxDuration: 20,



        },

    };



    let mediafilepicker = new Mediafilepicker();

    mediafilepicker.openVideoPicker(options);
    mediafilepicker.on("getFiles", res =>  {

        let results = res.object.get('results');
    
        console.dir(results);


        if (results) {

           
            for (let i = 0; i < results.length; i++) {



                let result = results[i];
                console.dir(result);



                let file = result.file;
                this.videoSrc= file;

                console.log(file);

            }
           
        }
        


    });



    mediafilepicker.on("error", function (res) {

        let msg = res.object.get('msg');

        console.log(msg);

    });



    mediafilepicker.on("cancel", function (res) {

        let msg = res.object.get('msg');

        console.log(msg);

    });
  
}
   }

`
.HTML
`<StackLayout>
    <VideoPlayer
    src="videoSrc"
    autoplay="true"
    controls="true"
    height="300"></VideoPlayer>
	<Button class="btn btn-primary" text="Play" (tap)="play()"></Button>
	<Button class="btn btn-primary" text="Pause" (tap)="pause()"></Button>
	<Button class="btn btn-primary" text="Go To 30 seconds" (tap)=" show()"></Button>
</StackLayout>


but still cant show the vid
`

**Comment by abdullahkhalidmahmood** [comment]
facing same issue here, i select image from gallery but unable to display it.
