### ISSUE TITLE
Allow picking a video or an image

### ISSUE THREAD

**Issue by Burgov** [jibon57/nativescript-mediafilepicker#78]
We were using version 1.0.7, and with the following configuration, it would allow us to pick a video or an image from a single picker:

```
                android: {
                    enableImagePicker: !types || types.contains('image'),
                    enableVideoPicker: !types || types.contains('video'),
                    enableCameraSupport: true,
                    mxcount: 1,
                }
```

However, with version 2.0.16, i can open _either_ the image picker _or_ the video picker. The alternative I guess would be to open the file picker, but I don't really want to manage all possible media file extensions.

Any way this can be supported again?

**Comment by jibon57** [comment]
No sorry, because native libraries had been changed in new version.
