### ISSUE TITLE
Can't create a video from the picker

### ISSUE THREAD

**Issue by Burgov** [jibon57/nativescript-mediafilepicker#8]
With these settings enabled (android):

```
                    enableImagePicker: true,
                    enableVideoPicker: true,
                    enableCameraSupport: true,
```

I was hoping to be able to create a video straight from the camera mode, but I'm only able to take pictures. The red "record" button is greyed out and not clickable. Is this something that could be fixed within the scope of this plugin or is it defined externally?

**Comment by jibon57** [comment]
This plugin isn't for video recording. For that purpose you can try this: https://github.com/triniwiz/nativescript-videorecorder
