### ISSUE TITLE
Folders showing up as files while using custom file picker

### ISSUE THREAD

**Issue by sgpatel5** [jibon57/nativescript-mediafilepicker#81]
See below image (On Android Emulator): - 

![image](https://user-images.githubusercontent.com/23383712/63100118-67b35c80-bf44-11e9-8772-aa5618c06346.png)

Code: - 

onChooseLocalFile() : void {
        let extensions = [];

        if (app.ios) {
            extensions = [kUTTypeContent]; // you can get more types from here: https://developer.apple.com/documentation/mobilecoreservices/uttype
        } else {
            extensions = ['*'];
        }

        let options: FilePickerOptions = {
            android: {
                extensions: extensions,
                maxNumberFiles: 1
            },
            ios: {
                extensions: extensions,
                multipleSelection: false
            }
        };

        let mediafilepicker = new Mediafilepicker(); 
        
        mediafilepicker.openFilePicker(options);

        mediafilepicker.on("getFiles", function (res) {
            let results = res.object.get('results');
            console.dir(results);
        });

        mediafilepicker.on("error", function (res) {
            let msg = res.object.get('msg');
            console.log(msg);
        });

        mediafilepicker.on("cancel", function (res) {
            let msg = res.object.get('msg');
            console.log(msg);
        });
        
    }

**Comment by jibon57** [comment]
You should add extension type `extensions = ['txt', 'pdf'];`

**Comment by dpdragnev** [comment]
Did you ever find a solution?  I am facing the same issue.

**Comment by erkanarslan** [comment]
It seems that the maintainer does not care about issues as long as it works for his own use case.
