### ISSUE TITLE
Android Application Crash when using Camera with NativeScript 6

### ISSUE THREAD

**Issue by ashraf-jabr** [jibon57/nativescript-mediafilepicker#82]
After taking photo and clicking accept in the preview screen then android application crash or restarted. Also during build process there is a warn about deprecated methods in NativeScript 6
`Camera_PreviewCallback.java uses or overrides a deprecated API`

**To Reproduce**
-Upgrade to NativeScript 6
- Try to pick a photo using the camera on Android

**Expected behavior**
Pick selected after accepting preview

**NativeScript Version:**
6.0.3

**Comment by jibon57** [comment]
Didn't follow the template

**Comment by virtualbjorn** [comment]
I don't think this plugin have ported to NS6.0 just yet so that might be why it is throwing an error like that.
