### ISSUE TITLE
App crashes when calling methods `openVideoPicker`, `openImagePicker`, `openAudioPicker` on iOS 13

### ISSUE THREAD

**Issue by ditoglez** [jibon57/nativescript-mediafilepicker#88]
**Describe the bug**
When calling one of the mentioned methods, `openVideoPicker`, `openImagePicker`, `openAudioPicker` on a new `mediafilepicker` instance the app crashes. Happens on iOS 13.0.

**To Reproduce**
Running the demo app from the repo, this behavior is reproducible over there also.

**Expected behavior**

App shouldn't crash, the video, image or audio picker should be presented.

**NativeScript Info(please run `tns info`):**
```
❯ tns info
✔ Getting NativeScript components versions information...
✔ Component nativescript has 6.1.2 version and is up to date.
⚠ Update available for component tns-core-modules. Your current version is 6.0.7 and the latest available version is 6.1.2.
⚠ Update available for component tns-android. Your current version is 6.1.1 and the latest available version is 6.1.2.
✔ Component tns-ios has 6.1.1 version and is up to date.
```

**Sample Code(please provide minimum code to reproduce problem):**
```
...
const mediafilepicker  = new MediaFilePicker();
mediafilepicker.openVideoPicker(this.options);
....
```

**Additional context**
Using `nativescript-angular` in my case but as mentioned is also reproducible using the demo in the repo.

Tried upgrading `tns-core-modules` to the latest version (6.1.2). Issue persists.

**Comment by jibon57** [comment]
@acivier-serial will you please have a look this issue? :)

**Comment by ditoglez** [comment]
@acivier-serial, @jibon57, hi guys, any updates on this?

**Comment by acivier-serial** [comment]
Hey @ditoglez,
I'll have a look, see if i can find a solution 👍

**Comment by Clonk-HTML5** [comment]
Hi @acivier-serial,
could you get any solution for this Issue ?
Thanks in advanced

**Comment by acivier-serial** [comment]
Hey there (sorry for the wait),

I found out that the problem came from the call of the `presentViewController` method inside a permission request's callback.
For instance (old way) : 
```typescript
PHPhotoLibrary.requestAuthorization(function (status) {
    if (status === PHAuthorizationStatus.Authorized) {
        t.presentViewController(controller, options.hostView);
    } else {
        t.msg = "Permission Error!";
        t.notify({
            eventName: 'error',
            object: t
        });
    }
});
```

The patch:
``` 
const main_queue = dispatch_get_current_queue();

PHPhotoLibrary.requestAuthorization(function (status) {
    if (status === PHAuthorizationStatus.Authorized) {
       // you have to tell iOS to use the main thread for UI render
        dispatch_async(main_queue, () => {
            this.presentViewController(controller, options.hostView);
        });
    } else {
        t.msg = "Permission Error!";
        t.notify({
            eventName: 'error',
            object: t
        });
    }
});
```

I'll made a PR soon

**Comment by asoufi** [comment]
I was having the same problem... as soon as I select an image or video, the app crashes. In my case, it was crashing because of: 1) I was selecting an image/video that was in my iCloud account and only its thumbnail was available on my phone, and 2) I had the wrong version of NativeScript. I was using 6.0.2 instead of 6.5.0. I removed node_modules folder, changed "version": "6.0.2" to "version": "6.5.0".
