### ISSUE TITLE
ERROR TypeError: format.replace is not a function

### ISSUE THREAD

**Issue by devlfm** [jibon57/nativescript-mediafilepicker#9]
Hi,

I'm not able to call "mediafilepicker.startFilePicker(options);", everytime throws that error.. am I the only one? I also tried to change emulator api, but the error remains, also instaled the debug apk on my phone and nothing shows up.

I'm using a very simple project. I was using "image-picker", but I need more options... 

Any help appretiated

**Comment by jibon57** [comment]
Common problem:

`this.mediafilepicker.on("getFiles", function (res: any) {`

`res:any` declaration

**Comment by devlfm** [comment]
Hi @jibon57 , I'm not understanding the solution.. I already have that:

> this.mediafilepicker.on("getFiles", (res: any) => {

and the error remains

**Comment by jibon57** [comment]
Share your full code for calling plugin here.
