### ISSUE TITLE
IOS present immediately closing (first start is working)

### ISSUE THREAD

**Issue by Clonk-HTML5** [jibon57/nativescript-mediafilepicker#92]
**Describe the bug**
The first start of for Example Filepicker, when app asks for permissions, is working but every time you try to start the Picker again it flickers and immediately closes.

I mentioned that as well in the imagepicker plugin.
Here are the Bugs related to: 
[289](https://github.com/NativeScript/nativescript-imagepicker/issues/289)
[251](https://github.com/NativeScript/nativescript-imagepicker/issues/251)

**To Reproduce**
IOS 13 open any Picker twice.
The first start, when app asks for permissions, is working but every time you try to start the Picker again it flickers and immediately closes.

**NativeScript Info(please run `tns info`):**
✔ Getting NativeScript components versions information...
⚠ Update available for component nativescript. Your current version is 6.2.0 and the latest available version is 6.2.2.
⚠ Update available for component tns-core-modules. Your current version is 6.1.2 and the latest available version is 6.2.1.
⚠ Update available for component tns-android. Your current version is 6.1.1 and the latest available version is 6.2.0.
⚠ Update available for component tns-ios. Your current version is 6.1.1 and the latest available version is 6.2.0.

Thanks

**Comment by jibon57** [comment]
Please try the latest version. New pull request was merged today: https://github.com/jibon57/nativescript-mediafilepicker/pull/91

**Comment by Clonk-HTML5** [comment]
yes i checked the PR and it also appears after updated.
The Mediafilepicker in total seems to be working only on IOS 13 it immediately closes.
Android seems to be working.

**Comment by jibon57** [comment]
@acivier-serial will you please have a look?

**Comment by acivier-serial** [comment]
I cannot reproduce the issue with the demo and iOS simulator 13.2. Could you please provide a repo to recreate the problem @Clonk-HTML5 ?

**Comment by Clonk-HTML5** [comment]
After a few more tests it seems that the plugin: [custom-bottomsheet](https://github.com/skhye05/nativescript-custom-bottomsheet) is causing this Problem.
If i open it with a normal Button tap everything works only if i open it with the bottomsheet it crashes. Thanks for your Time
