### ISSUE TITLE
Can't read variable IQMediaPickerControllerDelegate issue

### ISSUE THREAD

**Issue by vignesh-web** [jibon57/nativescript-mediafilepicker#93]
After installing the library, i was trying to choose a file and get the information about the file which i have chosen. 

While doing above, i was getting the error "Can't read variable `IQMediaPickerControllerDelegate`"

Please guide me to fix this issue.

**Comment by jibon57** [comment]
Try `tns platform remove ios` then `tns run ios`

**Comment by vignesh-web** [comment]
Sorry. It's not working. Again am getting same error. Please guide me on this.
