### ISSUE TITLE
ImagePicker return no file name on IOS

### ISSUE THREAD

**Issue by larxenne** [jibon57/nativescript-mediafilepicker#97]
I tried the demo and I cannot make the ImagePicker works on IOS
I tried on both an emulator and a real device.

The returned file path is always empty.
This is what I got for the console log

`CONSOLE LOG file:///app/main-view-model.ts:60:18:
==== object dump start ====
0: {
"type": "image",
"rawData": {}
}
==== object dump end ====
`
`CONSOLE LOG file:///app/main-view-model.ts:68:22: undefined`

**Comment by jibon57** [comment]
Hi,

Make sure that you aren't selecting icloud images. 

Thanks

**Comment by larxenne** [comment]
Hi,

No, the image is stored locally.
It works well with videos audio and other files, just the ImagePicker has this issue.

Everything works well on android

**Comment by marast78** [comment]
I have the same issue 👍 when I dump res.object.get('results') I get ⬇️ 

```typescript
[
  {
    "type": "image",
    "rawData": {}
  }
]
```

I've checked it using ios 13.3 (with android works fine)

**Comment by marast78** [comment]
@jibon57 is it possible that you will check it out soon? Or if not when could it be achievable?

**Comment by jibon57** [comment]
@acivier-serial will you please have a look this?

**Comment by coderaven** [comment]
Hi, is there any updates on this? And what is on IOS 13 that is possibly causing the issue? Thanks

**Comment by tylerablake** [comment]
Hi, 

I just came across this but I am using `"nativescript-imagepicker": "^6.1.2"` in a project and I can retrieve images in iOS 13. If someone looks into this it might be worth looking into that plugin's implementation for help.

**Comment by larxenne** [comment]
Hi,

I ended up doing the same and using nativescript-imagepicker plugin instead

**Comment by marast78** [comment]
I will start to use only verfied plugins. No more again not supported packages :ok_hand:

**Comment by coderaven** [comment]
Me too, I ended up using nativescript-imagepicker. However, I still think this plugin is promising but of course, as with any other open source projects - it needs to be maintained by the community.

Will try to make a pull request for the new changes if no one else does it in a couple of days.

**Comment by jibon57** [comment]
@coderaven thank you so much for your willingness to work. The native library isn't updating regularly & don't have that much expertise on native level too. I thinking to use [another library](https://github.com/zhangao0086/DKImagePickerController) to replace image & video picker. I am checking the possibilities now. This new library will support iCloud items too.

**Comment by kornerr** [comment]
Not sure if anyone still cares, StackOverflow has the issue covered here: https://stackoverflow.com/a/58335293

Basically, before iOS 12 filename was usually retrieved from `PHImageFileURLKey` key of info dictionary.
iOS 13 removed that key, so now people should use something like this instead:
```
let resourse = PHAssetResource.assetResources(for: self.phasset)
let url = resourse.first?.originalFilename
```
