### ISSUE TITLE
Use this on getFiles function...

### ISSUE THREAD

**Issue by SebastianCBA** [jibon57/nativescript-mediafilepicker#99]
Ok, the plugin works fine, but I need use "this" like:

> export default {
>   data() {
>     return {
>       testing: 'hello getFiles',
>           };
>   },
>   mounted() {
> ...

But when in getFiles function I do console.log(this.testing) I get undefined...

    mediafilepicker.on("getFiles", function (res) {
                  console.log(this.testing);

Can you help me to access a parent object

**Comment by jibon57** [comment]
Try this:

```
let t = this;
mediafilepicker.on("getFiles", function (res) {
              console.log(t.testing);
}

```
